export const FETCH_COMPANYVIEW_REQUEST = 'FETCH_COMPANYVIEW_REQUEST';
export const FETCH_COMPANYVIEW_SUCCESS = 'FETCH_COMPANYVIEW_SUCCESS';
export const FETCH_COMPANYVIEW_ERROR = 'FETCH_COMPANYVIEW_ERROR';