export const FETCH_SALESHISTORY_REQUEST = 'FETCH_SALESHISTORY_REQUEST';
export const FETCH_SALESHISTORY_SUCCESS = 'FETCH_SALESHISTORY_SUCCESS';
export const FETCH_SALESHISTORY_ERROR = 'FETCH_SALESHISTORY_ERROR';