export const FETCH_SALESCLIENT_REQUEST = 'FETCH_SALESCLIENT_REQUEST';
export const FETCH_SALESCLIENT_SUCCESS = 'FETCH_SALESCLIENT_SUCCESS';
export const FETCH_SALESCLIENT_ERROR = 'FETCH_SALESCLIENT_ERROR';