export const FETCH_SALESREVIEW_REQUEST = 'FETCH_SALESREVIEW_REQUEST';
export const FETCH_SALESREVIEW_SUCCESS = 'FETCH_SALESREVIEW_SUCCESS';
export const FETCH_SALESREVIEW_ERROR = 'FETCH_SALESREVIEW_ERROR';