export const FETCH_SCHEDULE_DETAIL_REQUEST = 'FETCH_SCHEDULE_DETAIL_REQUEST';
export const FETCH_SCHEDULE_DETAIL_SUCCESS = 'FETCH_SCHEDULE_DETAIL_SUCCESS';
export const FETCH_SCHEDULE_DETAIL_ERROR = 'FETCH_SCHEDULE_DETAIL_ERROR';